language: node_js
node_js:
  - "0.11"
script: "make test-travis"
before_script:
  - "npm install -g yo"
  - "npm install -g generator-kona"
  - "make test-app"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"